export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verifyRegistration: '/auth/register/verify',
    resendRegistrationOtp: '/auth/register/resend-otp',
    verifyToken: '/auth/verify',
    refreshToken: '/auth/refresh',
    requestPasswordReset: '/auth/password-reset/request',
    confirmPasswordReset: '/auth/password-reset/confirm',
  },
  profile: {
    root: '/profile',
    changePassword: '/profile/change-password',
  },
  companyDocuments: {
    uploadUrl: '/company-documents/upload-url',
    complete: (documentId: string) => `/company-documents/${encodeURIComponent(documentId)}/complete`,
    detail: (documentId: string) => `/company-documents/${encodeURIComponent(documentId)}`,
    retry: (documentId: string) => `/company-documents/${encodeURIComponent(documentId)}/retry`,
  },
  templates: { root: '/templates' },
  billing: {
    checkoutSessions: '/billing/checkout-sessions',
    checkoutSession: (sessionId: string) =>
      `/billing/checkout-sessions/${encodeURIComponent(sessionId)}`,
    subscriptions: '/billing/subscriptions',
    history: '/billing/history',
    portalSessions: '/billing/portal-sessions',
    cancelSubscription: (subscriptionId: string) =>
      `/billing/subscriptions/${encodeURIComponent(subscriptionId)}/cancel`,
  },
  consents: {
    forms: '/consents/forms',
    form: (formId: string) => `/consents/forms/${encodeURIComponent(formId)}`,
    records: '/consents/records',
    activityLogs: '/consents/activity-logs',
    publicForPolicy: (slug: string) => `/consents/public/policy/${encodeURIComponent(slug)}`,
    publicResponses: (token: string) => `/consents/public/${encodeURIComponent(token)}/responses`,
    events: (recordId: string) => `/consents/records/${encodeURIComponent(recordId)}/events`,
    withdraw: (recordId: string) => `/consents/records/${encodeURIComponent(recordId)}/withdraw`,
  },
  policies: {
    root: '/policies',
    byId: (policyId: string) => `/policies/${encodeURIComponent(policyId)}`,
    changeRequests: (policyId: string) => `/policies/${encodeURIComponent(policyId)}/change-requests`,
    changeRequest: (policyId: string, requestId: string) => `/policies/${encodeURIComponent(policyId)}/change-requests/${encodeURIComponent(requestId)}`,
    publicBySlug: (slug: string) => `/policies/public/${encodeURIComponent(slug)}`,
    publicBySlugAndLanguage: (slug: string, language: 'th' | 'en') => `/policies/public/${encodeURIComponent(slug)}/${language}`,
    publicConsent: (slug: string) => `/policies/public/${encodeURIComponent(slug)}/consent`,
    publicAcknowledgement: (slug: string) => `/policies/public/${encodeURIComponent(slug)}/acknowledgement`,
    activityLogs: (policyId: string) => `/policies/${encodeURIComponent(policyId)}/activity-logs`,
  },
  legal: {
    dashboard: '/legal/dashboard',
    submissions: '/legal/submissions',
    submission: (slug: string) => `/legal/submissions/${encodeURIComponent(slug)}`,
    changeRequests: '/legal/change-requests',
    changeRequest: (requestId: string) => `/legal/change-requests/${encodeURIComponent(requestId)}`,
  },
  admin: {
    overview: '/admin/overview',
    merchants: '/admin/merchants',
    merchant: (merchantId: string) => `/admin/merchants/${encodeURIComponent(merchantId)}`,
    merchantStatus: (merchantId: string) => `/admin/merchants/${encodeURIComponent(merchantId)}/status`,
    subscriptions: '/admin/subscriptions',
    payments: '/admin/payments',
    payment: (paymentId: string) =>
      `/admin/payments/${encodeURIComponent(paymentId)}`,
    policies: '/admin/policies',
    policy: (policyId: string) => `/admin/policies/${encodeURIComponent(policyId)}`,
    assignLegal: (policyId: string) => `/admin/policies/${encodeURIComponent(policyId)}/assign-legal`,
    logs: '/admin/monitoring/logs',
    activityLogs: '/admin/monitoring/activity-logs',
    merchantActivity: '/admin/monitoring/merchant-activity',
    analytics: '/admin/analytics',
    legalUsers: '/admin/legal-users',
    legalUser: (legalUserId: string) => `/admin/legal-users/${encodeURIComponent(legalUserId)}`,
    legalUserStatus: (legalUserId: string) => `/admin/legal-users/${encodeURIComponent(legalUserId)}/status`,
    legalWorkload: '/admin/legal-workload',
    legalReviews: '/admin/legal-reviews',
    templates: '/admin/templates',
    template: (templateId: string) => `/admin/templates/${encodeURIComponent(templateId)}`,
    companyDocuments: '/admin/company-documents',
    companyDocument: (documentId: string) => `/admin/company-documents/${encodeURIComponent(documentId)}`,
    companyDocumentViewUrl: (documentId: string) => `/admin/company-documents/${encodeURIComponent(documentId)}/view-url`,
    approveCompanyDocument: (documentId: string) => `/admin/company-documents/${encodeURIComponent(documentId)}/approve`,
    rejectCompanyDocument: (documentId: string) => `/admin/company-documents/${encodeURIComponent(documentId)}/reject`,
    retryCompanyDocumentArchive: (documentId: string) => `/admin/company-documents/${encodeURIComponent(documentId)}/archive/retry`,
  },
  dashboard: {
    stats: '/dashboard/stats',
    activities: '/dashboard/activities',
  },
  upload: {
    root: '/upload',
  },
} as const
